project:
  type: website

website:
  title: "triathlon"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - workout-calendar.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
